# version: '3'

# services:
#   db:
#     image: flipkart-postgres
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: magidexter
#       POSTGRES_DB: Flipkart

#   web:
#     build: .
#     command: npm start
#     ports:
#       - "4000:3000"
#     depends_on:
#       - db

version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: magidexter
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    command: npm start
  db:
    image: flipkart-postgres
    environment:
      POSTGRES_DB: Flipkart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magidexter
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: