version: "3.9"
services:
  app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mageshsk16/app:latest
    depends_on:
      - db
    ports:
      - "4000:3000"
    volumes:
      - .:/app
    command: npm start
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: Flipkart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: magidexter
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: